# Generated by Django 5.0 on 2025-02-05 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_room_created_by_room_users_amount_alter_message_room"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="joined_users",
            field=models.ManyToManyField(
                blank=True, related_name="joined_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
