# Generated by Django 5.0 on 2025-02-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_room_joined_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reactions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
