# Generated by Django 5.0 on 2025-01-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfriends",
            unique_together=set(),
        ),
    ]
