# Generated by Django 5.0 on 2025-01-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_userprofile_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
    ]
